apiVersion: v1
kind: Service
metadata:
  name: application-front
  labels:
    app: application-front
spec:
  type: LoadBalancer
  selector:
    app: application-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
